### ISSUE TITLE
Building of EUROPE-Map requires manual intervension

### ISSUE THREAD

**Issue by teddyimsuff** [freizeitkarte/fzk-mde-garmin#7] opened 2017-06-01 07:25 UTC
- All previously required steps did run fine
```
PS C:\PATH\fzk-mde-garmin-LATEST\Freizeitkarte-Entwicklung> perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max build EUROPE

mt.pl - Map Tool for creating Garmin maps, 1.3.13 - 2016/11/11


Checking the Development Environment...

Action:     build
            5.  build map files (img, mdx, tdb)
Map:        Freizeitkarte_EUROPE (8888)
Language:   Deutsch (de)
CodePage:   1252
Typ file:   freizeit.TYP
Style Dir:  style/fzk
Elevation:  20 m
Map type:   parent map
Release:    17.05 / 1705



Creating C:/PATH/fzk-mde-garmin-LATEST/Freizeitkarte-Entwicklung/work/Freizeitkarte_EUROPE_de/Freizeitkarte_EUROPE.cfg ...
Can't open C:/PATH/fzk-mde-garmin-LATEST/Freizeitkarte-Entwicklung/work/Freizeitkarte_EUROPE_de/Freizeitkarte_EUROPE.cfg: No such file or directory
```

- the folter "../work/Freizeitkarte_EUROPE_de/" has to be created manually in the files system. should be done automatically by the perl script.
- CFG-file has to be created manually via "cfg"-command. should be done automatically by the perl script in a previous step.

```
PS C:\PATH\fzk-mde-garmin-LATEST\Freizeitkarte-Entwicklung> perl .\mt.pl --continuedownload --ram=80000 --cores=max --language=de cfg EUROPE

mt.pl - Map Tool for creating Garmin maps, 1.3.13 - 2016/11/11


Checking the Development Environment...

Action:     cfg
            A. create individual cfg file
Map:        Freizeitkarte_EUROPE (8888)
Language:   Deutsch (de)
CodePage:   1252
Typ file:   freizeit.TYP
Style Dir:  style/fzk
Elevation:  20 m
Map type:   parent map
Release:    17.05 / 1705



Creating C:/PATH/fzk-mde-garmin-LATEST/Freizeitkarte-Entwicklung/work/Freizeitkarte_EUROPE_de/Freizeitkarte_EUROPE.cfg ...
Done

```
- Building the Europe-Map via "build"-command will now work

**Comment by keenonkites** [comment] 2017-06-01 07:57
Europe is not ment to be build as a complete map (must be huge, and very timeconsuming to be built, I assume). The OSM data of it is only needed for extracts we create on our own, like DEU+ or CHE+ or similar.
This might serve as an explanation why certain things may fail in case of trying to build Europe.

I, personally, don't think it makes sense to build Europa as a whole, it is quite 'unhandy'.... therefore I'm not sure in which direction to go:
- fixing it that building Europe is possible
- fixing it that building Europe is prevented
- doing nothing.

Actually right now I'm tending towards the last option.... but if I have some time I'll check what the different options would mean.

Thanks anyway for letting us know.

**Comment by teddyimsuff** [comment] 2017-06-01 08:44
I love the Europe Map for trans-border traveling. It's far easier to plan routes without switching the map all the time and you don't need to cut the route into country specific pieces which i find very annoying. That was the reason why i build the Europe Map in the first place.

The only problems I had are the two reported above. I suspect this is due to the fact that EUROPE is a special map (type 1). Fixing it is just a question of adding the folder and CFG.

I realize that hardly anyone will ever build this map, therefor:
- Doing nothing is fine, but maybe add a comment in the mt.pl so people know about the issue and how to get around it.
- Fixing it would be great. However I understand why you may not wanna do that.
- Preventing EUROPE from building is a bad solution I think. You could however add a function into mt.pl that prevents the map from being build, but can be commented out as kind of an "expert"-function to restore the current state.

In case you wounder:
- building the map requires about 60-80GB RAM (can be SWAP-Space, but should be on SSD)
- it takes 2-3 days on a notebook with i7. That doesn't bother me personally. I'll just start and wait
- NSIS will fail due to size, but you can export as gmap and then install via Javawa GMTK (http://www.javawa.nl/gmtk_en.html)

**Comment by keenonkites** [comment] 2017-06-01 09:20
borderless travelling: that's why we have the Plus Maps like DEU+ and similar... ;-)

Thanks for the details about the building times and the requierements needed for that.... quite impressive.

BTW: you don't need Javawa GMTK to install the final GMAP format map: you can either move the GMAP folder into the correct location or create a windows shortcut there, pointing to the real location... nothing more needed.

Please provide all the commands you issue for building the EUROPE MAP (just the commands, no output needed, asI know it fails at 'build')... as there are several ways to get there.
It's just to make sure we don't miss an easy fix.

Additional Question: you have elevation lines on your Europe Map ?

**Comment by teddyimsuff** [comment] 2017-06-01 10:00
But the Plus-Maps won't help, if you travel from Denmark to Italy and want to see the hole route on one map.

Thanks for the Link-info, I'll try that.
Elevation lines are present on the Europe map and work fine.

Here are the commands for powershell:

```
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max bootstrap
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max create EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max fetch_osm EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max fetch_ele EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max join EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max split EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max build EUROPE
-> ERROR, see above
mkdir .\work\Freizeitkarte_EUROPE_de
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max cfg EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max build EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max gmap EUROPE
-> will fail due to missing target directory
mkdir .\work\Freizeitkarte_EUROPE_de
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max gmap EUROPE
perl .\mt.pl --continuedownload --ram=80000 --language=de --cores=max zip EUROPE
```

**Comment by keenonkites** [comment] 2017-06-01 10:08
Plus-Maps: ok... long trip... ;-)
Elevation: ok good.
Commands: I see, thanks... all clear

... not sure when I will have time to check but I'll have a look at it

**Comment by teddyimsuff** [comment] 2017-06-01 10:58
no problem, I have a workflow that puts out the map I want, so I'm fine. Just so you know about the issue!

**Comment by teddyimsuff** [comment] 2017-06-02 09:36
I forgot: you will also have to add the target directory under "install". i edited the post above

**Comment by keenonkites** [comment] 2017-06-02 11:23
one thing to your actual workflow:
- you can skip the action 'cfg' as 'cfg' is also part of 'build'

I've updated mt.pl to 
- make sure that all needed directories are around also for your 'special cases'
- issue warning (together with a 10 sec forced pause to be able to stop execution) in case of officially 'unsupported' combination of actions and maptypes

Please feel free to test the new version.... you just have to download the develop branch as it's not yet in any official release of the development environment.

And a typ for your tests:
Don't do the tests with EUROPE as this would take too long. You can use the map CHE_R which is the size of Switzerland and therefore much smaller as EUROPE, but with the same behaviour (it's a so called parent map from which we extract our own extracts).

If all looks fine for you we can close this issue.

**Comment by ChristianKraemer** [comment] 2017-06-02 11:33
Out of curiosity: Is Great Britain included? Are there routing-problems caused by left- and right-hand traffic in one map?

**Comment by teddyimsuff** [comment] 2017-06-02 12:08
GB is included and works fine as far as I can tell. Routing happens on the LEFT.
Since there is no border in Europe where driving changes from left to right I cannot test this.

So far routing has worked fine for me. The only thing i noticed is that instead on telling me to go straight for 100 km on the Autobahn or any other major A-road, it tells me to keep left at every exit. It's not a problem but a little annoying. 

I'll test the DEV-branche now.

**Comment by teddyimsuff** [comment] 2017-06-02 16:43
I tested it and everything worked fine.
There was no CHE_R ele map so I used CHE and renamed it.

So far, all is well and the ticket can be closed.

**Comment by keenonkites** [comment] 2017-06-02 16:45
Great... thanks for testing.
... and yes, sorry, forgot to mention that there is no ele file for CHE_R, but you did the correct thing: 'abusing' normal CHE... ;-)

**Closed as completed by keenonkites** 2017-06-02 16:45 UTC
